### ISSUE TITLE
"Framing error"

### ISSUE THREAD

**Issue by repvik** [sparkfun/HaterMatic#1]
"// Oddly enough, for nickels and dimes, the data coming out of the coin
    //  acceptor has a framing error: the last bit is a little too long. The
    //  SoftwareSerial receive function doesn't seem to wait for the stop bit
    //  (which will always be one), so it starts another read when it sees the
    //  extra long final bit, then reads all ones, which is interpreted as -1.
    //  We want to reject any result which is -1, since that's a nonsense coin
    //  value anyway."

This is incorrect. It is not a framing error, it is the result of incorrect serial settings. The coin acceptor does not use 9600 8N1, it uses 9600 8E1. That's why you get an "extra long bit" on some coins.

The datasheet specifies this, in an awkward machine-translated way.

**Comment by mhord** [comment]
Good to know, but not helpful since SoftwareSerial doesn't support parity.
